Package.require('Server/Core.lua')
Package.require('Server/Player/CPlayer.lua')
Package.require('Server/Player/Character/CCharacter.lua')
Package.require('Server/Inventory/Inventory.lua')
Package.require('Server/Banking/Account.lua')